---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lgtm
  namespace: flux-system
spec:
  targetNamespace: monitoring
  chart:
    spec:
      chart: lgtm-distributed
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: 2.1.0
  interval: 10m0s
  values:
    grafana:
      grafana.ini:
        log:
          format: json
          level: debug

