
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lgtm
  namespace: flux-system
spec:
#  dependsOn:
#    - name: kafka
  interval: 10m0s
  path: ./releases/lgtm
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
