
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: inner-aggregator-vector
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./releases/inner-aggregator-vector
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
