apiVersion: v1
kind: Service
metadata:
  labels:
    io.service: akhq
  name: akhq
  namespace: queuing
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.service: akhq
