---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kafka
  namespace: flux-system
spec:
  dependsOn:
    - name: kafka-operator
    - name: kube-prometheus-stack
  interval: 10m0s
  path: ./releases/kafka
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
