---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: supporting-infra
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./supporting-infra
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
