---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: etcd-buf
  namespace: flux-system
spec:
  targetNamespace: queuing
  chart:
    spec:
      chart: etcd
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 11.1.6
  interval: 10m0s
  values:
    replicaCount: 3
    persistence:
      enabled: true
      size: 1Gi
      storageClass: ""
    autoCompactionMode: periodic
    autoCompactionRetention: 30s
    removeMemberOnContainerTermination: false
    resourcesPreset: none
    auth:
      rbac:
      create: false
      enabled: false
    token:
      enabled: false
    metrics:
      useSeparateEndpoint: true
    customLivenessProbe:
      httpGet:
        port: 9090
        path: /livez
        scheme: "HTTP"
      initialDelaySeconds: 10
      periodSeconds: 30
      timeoutSeconds: 15
      failureThreshold: 10
    customReadinessProbe:
      httpGet:
        port: 9090
        path: /readyz
        scheme: "HTTP"
      initialDelaySeconds: 20</span>
      timeoutSeconds: 10</span>
    extraEnvVars:
      - name: ETCD_LISTEN_CLIENT_HTTP_URLS
        value: "http://0.0.0.0:8080"

