
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: supporting-infra-ns
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./supporting-infra/namespaces
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
