apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.service: bufstream-claim0
  name: bufstream-claim0
  namespace: queuing
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
