apiVersion: v1
kind: Service
metadata:
  labels:
    io.service: bufstream
  name: bufstream
  namespace: queuing
spec:
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
  selector:
    io.service: bufstream
