
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: supporting-infra-ingress
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./supporting-infra/ingress
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
