apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./kafka/ks.yaml
- ./lgtm/ks.yaml
- ./k8status/ks.yaml
#- ./bufstream/ks.yaml
- ./akhq/ks.yaml
- ./edge-telemetry-collector/ks.yaml
- ./inner-aggregator-collector/ks.yaml