---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: inner-aggregator-collector
  namespace: flux-system
spec:
  dependsOn:
    - name: kafka
  interval: 10m0s
  path: ./releases/inner-aggregator-collector
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
