---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka-operator
  namespace: flux-system
spec:
  targetNamespace: queuing
  chart:
    spec:
      chart: strimzi-kafka-operator
      sourceRef:
        kind: HelmRepository
        name: strimzi
      version: 0.40.0
  interval: 10m0s
  values:
    watchAnyNamespace: true
